// Conformance gate (PRD testing seam 1). Every vendored ario.events/v1
// corpus vector must be reproduced BYTE-FOR-BYTE by this package's write
// path: record JCS bytes, payload hash, envelope-for-signing bytes,
// signature, and the complete-envelope upload bytes. The vectors are
// generated by ar-io-proof's independent Python generator (jcs + pynacl), so
// agreement here is cross-language conformance, not self-confirmation.

import { readFileSync, readdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { bytesToHex, leafHash, merkleRoot, verifyInclusion } from "@ar.io/proof";
import { describe, expect, it } from "vitest";

import { buildEnvelope } from "../src/envelope";
import { LocalEd25519Signer } from "../src/signer";
import type { Environment, EventRecord } from "../src/types";

const VECTORS_DIR = join(
  dirname(fileURLToPath(import.meta.url)),
  "..",
  "test-vectors",
  "ario.events-v1",
);

interface EventsVector {
  vector_id: string;
  spec_version: string;
  fixed_keypair: { ed25519_seed_hex: string; ed25519_public_hex: string };
  inputs: {
    event_record: EventRecord;
    envelope_pre_signature: {
      spec_version: string;
      event_id: string;
      signed_at: string;
      environment: Environment;
      payload_ref?: string;
    };
  };
  expected_outputs: {
    payload_jcs_bytes_hex: string;
    payload_hash_hex: string;
    envelope_for_sig_jcs_bytes_hex: string;
    signature_hex: string;
    envelope_jcs_bytes_hex: string;
  };
  merkle?: {
    leaves: { envelope_jcs_bytes_hex: string; leaf_hash_hex: string }[];
    expected_root_hex: string;
    inclusion_proofs: { leaf_index: number; audit_path_hex: string[] }[];
  };
}

const vectors: EventsVector[] = readdirSync(VECTORS_DIR)
  .filter((f) => f.endsWith(".json"))
  .sort()
  .map((f) => JSON.parse(readFileSync(join(VECTORS_DIR, f), "utf8")));

describe.each(vectors.map((v) => [v.vector_id, v] as const))(
  "corpus vector %s",
  (_id, v) => {
    it("is reproduced byte-for-byte by buildEnvelope", async () => {
      const pre = v.inputs.envelope_pre_signature;
      const built = await buildEnvelope({
        record: v.inputs.event_record,
        signer: LocalEd25519Signer.fromSeedHex(v.fixed_keypair.ed25519_seed_hex),
        environment: pre.environment,
        eventId: pre.event_id,
        signedAt: pre.signed_at,
        ...(pre.payload_ref !== undefined ? { payloadRef: pre.payload_ref } : {}),
      });
      const out = v.expected_outputs;
      expect(bytesToHex(built.recordBytes)).toBe(out.payload_jcs_bytes_hex);
      expect(built.payloadHash).toBe(out.payload_hash_hex);
      expect(built.envelope.public_key).toBe(v.fixed_keypair.ed25519_public_hex);
      expect(built.envelope.signature).toBe(out.signature_hex);
      expect(bytesToHex(built.envelopeBytes)).toBe(out.envelope_jcs_bytes_hex);
    });
  },
);

describe("checkpoint merkle block (profile §6 leaf definition)", () => {
  const v = vectors.find((x) => x.merkle !== undefined);

  it("reproduces leaf hashes, root, and inclusion proofs via @ar.io/proof", async () => {
    expect(v).toBeDefined();
    const m = v!.merkle!;
    const leafHashes: Uint8Array[] = [];
    for (const leaf of m.leaves) {
      // Leaf = RFC 9162 leaf hash over the complete signed envelope's JCS
      // bytes. Recompute from the envelope bytes, not the recorded hash.
      const envelopeBytes = Uint8Array.from(Buffer.from(leaf.envelope_jcs_bytes_hex, "hex"));
      const lh = await leafHash(envelopeBytes);
      expect(bytesToHex(lh)).toBe(leaf.leaf_hash_hex);
      leafHashes.push(lh);
    }
    const root = await merkleRoot(leafHashes);
    expect(bytesToHex(root)).toBe(m.expected_root_hex);
    expect(v!.inputs.event_record.event.merkle_root).toBe(m.expected_root_hex);

    for (const proof of m.inclusion_proofs) {
      const ok = await verifyInclusion(
        leafHashes[proof.leaf_index]!,
        proof.leaf_index,
        leafHashes.length,
        proof.audit_path_hex.map((h) => Uint8Array.from(Buffer.from(h, "hex"))),
        root,
      );
      expect(ok, `inclusion proof leaf ${proof.leaf_index}`).toBe(true);
    }
  });
});
